apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: heart-api-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: heart-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
