apiVersion: v1
kind: Service
metadata:
  name: heart-api-service
  labels:
    app: heart-api
spec:
  type: NodePort
  selector:
    app: heart-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32037
